### ISSUE TITLE
Error establishing database connection.

### ISSUE THREAD

**Issue by v3nt** [urre/wordpress-nginx-docker-compose#12]
Great tutorial! 

Everything works except the Wp install can't connect to the database.

https://myapp.local

Gives me

````
Warning: mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/web/wp/wp-includes/wp-db.php on line 1612 Warning: mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/web/wp/wp-includes/wp-db.php on line 1612

php_network_getaddresses: getaddrinfo failed: Name or service not known

````

or

````
Warning: mysqli_real_connect(): (HY000/2002): Connection refused in /var/www/html/web/wp/wp-includes/wp-db.php on line 1612
Connection refused
````

```
Error establishing a database connection
This either means that the username and password information in your wp-config.php file is incorrect or we can’t contact the database server at db:3306. This could mean your host’s database server is down.

Are you sure you have the correct username and password?
Are you sure that you have typed the correct hostname?
Are you sure that the database server is running?
```

All DB credentials are the same. Changed everything to 'wordpress' but the wp install still wont connect. Is there a way to see what the containers are setting the login info as? Or see the generated wp-config.php settings?

I tried adding a phpmyadmin container. It was visible but couldn't log in.

This is by far the closest tutorial for what i need & would be amazing to get over this final hurdle. I've been using docker a lot and not had this issue before. However none of my previous projects use a local domain or ssl.

D.

docker-compose.yml

````
version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: myapp-nginx
    ports:
      - '8084:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - wordpress
    restart: always

  db:
    image: mysql:5.7
    container_name: myapp-mysql
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
    # ports:
    #   - '3306:3306'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=wordpress
    depends_on:
      - db
    restart: always

  composer:
    image: composer/composer
    container_name: myapp-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
````

.env

````
DB_HOST=db:3306
DB_NAME=wordpress
DB_USER=wordpress
DB_PASSWORD=wordpress
# DB_PREFIX=wp_

WP_ENV=development
WP_HOME=https://myapp.local
WP_SITEURL=${WP_HOME}/wp

# Generate your keys here: https://roots.io/salts.html
AUTH_KEY='generateme'
SECURE_AUTH_KEY='generateme'
LOGGED_IN_KEY='generateme'
NONCE_KEY='generateme'
AUTH_SALT='generateme'
SECURE_AUTH_SALT='generateme'
LOGGED_IN_SALT='generateme'
NONCE_SALT='generateme'

````

feedback during build

````
docker-compose up -d --force-recreate --build
Creating network "wordpress-nginx-docker-compose_default" with the default driver
Building wordpress
Step 1/4 : FROM urre/wordpress-nginx-docker-compose-image
 ---> c3797de1da74
Step 2/4 : RUN curl -o /bin/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
 ---> Using cache
 ---> 2c780d637b20
Step 3/4 : RUN chmod +x /bin/wp-cli.phar
 ---> Using cache
 ---> 632824aec449
Step 4/4 : RUN cd /bin && mv wp-cli.phar wp
 ---> Using cache
 ---> 7a7b5fb81401

Successfully built 7a7b5fb81401
Successfully tagged wordpress-nginx-docker-compose_wordpress:latest
Creating myapp-composer  ... done
Creating myapp-mysql    ... done
Creating myapp-wordpress ... done
Creating myapp-nginx     ... done
````
