### ISSUE TITLE
Issues working with Traefik

### ISSUE THREAD

**Issue by shaneparsons** [urre/wordpress-nginx-docker-compose#13]
Following the steps exactly everything seems to work fine... However, I'm having trouble once I try to get this to work with Traefik.

Since Traefik uses port 80 and 443, I usually just remove the port section from anything else trying to reserve those ports (in this case nginx) and it usually doesn't cause me any problems. But with this setup it's been giving me 'not found' and 'gateway' errors.

Trying to trace the logs down to the source of the problem, this often comes up:
```
[emerg] 1#1: host not found in upstream "wordpress" in /etc/nginx/conf.d/wordpress_ssl.conf:43
myapp-nginx  | nginx: [emerg] host not found in upstream "wordpress" in /etc/nginx/conf.d/wordpress_ssl.conf:43
```
Which refers to this line in the nginx conf
```
fastcgi_pass wordpress:9000;
```
I've tried a number of this to try to get past this (I won't share them all), but this is my modified nginx conf:
```conf
server {
    listen      80;
    server_name myapp.local;

    # listen      443           ssl http2;
    # listen [::]:443           ssl http2;
    # server_name               myapp.local www.myapp.local;

    # add_header                Strict-Transport-Security "max-age=31536000" always;

    # ssl_session_cache         shared:SSL:20m;
    # ssl_session_timeout       10m;

    # ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    # ssl_prefer_server_ciphers on;
    # ssl_ciphers               "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:!ADH:!AECDH:!MD5;";

    root /var/www/html/web;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # ssl_certificate           /etc/certs/myapp.local.crt;
    # ssl_certificate_key       /etc/certs/myapp.local.key;

    # client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```
I disabled the SSL stuff to make it easier to debug... Any ideas on why I'm getting these issues / what I can do to get around them?

**Comment by shaneparsons** [comment]
I tried so many different things that I'm not sure which step in particular fixed the main issue, but here's my `.env` / `docker-compose.yml`, just in case it can help somebody else:

```properties
DB_DATABASE=bedrock
DB_USER=bedrock
DB_PASSWORD=bedrock
DB_ROOT_PASSWORD=bedrock
SITE_URL=bedrock.localhost
```
```yml
version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: bedrock-mysql
    # restart: always
    networks:
      - bedrock
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - db_data:/var/lib/mysql
    expose:
      - '3306'
  
  nginx:
    image: nginx:latest
    container_name: bedrock-nginx
    # restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html/:rw,cached
      # - ./certs:/etc/certs
    networks:
      - bedrock
      - traefik
    labels:
      - traefik.http.routers.bedrock.rule=Host(`${SITE_URL}`)
    depends_on:
      - php
    expose:
      - '80'

  php:
    container_name: bedrock-php
    build:
      context: .
      dockerfile: dockerfile
    # restart: always
    volumes:
      - ./app:/var/www/html/:rw,cached
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - bedrock
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    expose:
      - '9000'

  composer:
    image: composer/composer
    container_name: bedrock-composer
    networks:
      - bedrock
    restart: 'no'
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/:rw,cached

networks:
  traefik:
    external: true
  bedrock:
    external: false

# volumes:
#   db_data:
```

If I were to guess, I'd say the `expose` and `networks` additions are the main points of interest.

NOTE: If you intend on copy / pasting this directly somewhere, I've changed the naming of some of the stuff.
