### ISSUE TITLE
How to make work with BrowserSync proxy

### ISSUE THREAD

**Issue by aaronjpitts** [urre/wordpress-nginx-docker-compose#44]
Hey @urre,

This is a great project, so thank you for making it. I'm trying to get browsersync to work to help with the theme's local development. I use the Sage theme also from the Roots stack. Normally you set the dev domain in the [webpack.mix.js file](https://github.com/roots/sage/blob/10.0.0-dev/webpack.mix.js) and run `yarn start` from the theme directory.

I added a node service for this to docker-compose.yml:
```
  node:
    image: node:12-slim
    container_name: ${APP_NAME}-node
    working_dir: /var/www/html/web/app/themes/sage
    restart: 'no'
    volumes:
      - ../site:/var/www/html:rw,cached
```

So I can build the theme files by running: `docker-compose run node yarn build` but running `docker-compose run node yarn start` which starts the development mode using browsersync is not working. Browsersync gives the `localhost:3000` URL to look at your site on to see the changes, but obviously this is not working. I'm not sure how to proxy this development URL from the docker container to be used on my machine. I've tried several things but I've ran in to a brick wall. I was wondering if you had an idea on how to get this set up?

Thanks again!
Aaron
