### ISSUE TITLE
404 NGINX Error Permission Denied

### ISSUE THREAD

**Issue by M-Marbouh** [urre/wordpress-nginx-docker-compose#55]
Hi, thanks for this great stack,
I don't have good experience in Docker but I tried to follow the steps in the readme file,
The trouble I have is related to permissions, I am running this stack in Linux Mint, but NGINX is complaining about permissions only for WordPress, PHPMyAdmin, and MailHog are up and running fine. Not sure what I missed here:

Error when trying to access WordPress:
`404 Not Found`

Error Log:
```
[crit] 8#8: *2 stat() "/var/www/html/web/" failed (13: Permission denied), client: <My_IP_ADDRESS>, server: mydomain.local, request: "GET / HTTP/2.0", host: "university.local"
[crit] 8#8: *2 stat() "/var/www/html/web/" failed (13: Permission denied), client: <My_IP_ADDRESS>, server: mydomain.local, request: "GET / HTTP/2.0", host: "university.local"
[crit] 8#8: *2 stat() "/var/www/html/web/index.php" failed (13: Permission denied), client: <My_IP_ADDRESS>, server: mydomain.local, request: "GET / HTTP/2.0", host: "university.local"
```
Nginx config:
```
server {
    listen      80;
    listen [::]:80;
    server_name $domain;

    location / {
        rewrite ^ https://$host$request_uri? permanent;
    }
}

server {
    listen      443           ssl http2;
    listen [::]:443           ssl http2;
    server_name               $domain www.$domain;

    add_header                Strict-Transport-Security "max-age=31536000" always;

    ssl_session_cache         shared:SSL:20m;
    ssl_session_timeout       10m;

    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:!ADH:!AECDH:!MD5;";

    root /var/www/html/web;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ssl_certificate           /etc/certs/$domain.crt;
    ssl_certificate_key       /etc/certs/$domain.key;

    gzip on;
    gzip_http_version 1.0;
    gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_min_length 256;
  gzip_types
    text/css
    text/javascript
    text/xml
    text/plain
    text/x-component
    application/javascript
    application/json
    application/xml
    application/rss+xml
    font/truetype
    font/opentype
    application/vnd.ms-fontobject
    image/svg+xml;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```
Docker-compose.yml:
```
version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/tmp/default.template
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - wordpress
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'

  mysql:
    image: mariadb
    container_name: ${APP_NAME}-mysql
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - '3306:3306'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '8080:80'
    links:
      - mysql:mysql

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
```
Any help is appreciated.

Thanks again
