### ISSUE TITLE
domain.local is not resolved in composer container using satispress local composer repository

### ISSUE THREAD

**Issue by valdestron** [urre/wordpress-nginx-docker-compose#57]
While using composer I came up with a need to setup satispress for my custom themes or plugins.

composer.json
```
{
...
"repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org",
      "only": ["wpackagist-plugin/*", "wpackagist-theme/*"]
    },
    {
      "type": "composer",
      "url": "https://domain.local/satispress/"
    }
  ],
...
  "require": {
    ...
    "custompackage/package": "*"
  }
}
```

While running command:
```
docker-compose run composer update
```

Getting error:

```
[Composer\Downloader\TransportException]                           
  Failed to connect to domain.local port 443: Connection refused
```

I guess composer container uses docker network DNS server instead of host. Also composer container does not have root ca's in order to access https://domain.local

**Comment by valdestron** [comment]
I rebuilded original composer container to support root ca's so quick fix would be to update docker-compose.yaml like this, dont forget to turn on pretty urls in wordpress using satispress.

```
...
  composer:
    image: valdestrijus/composer-ssl
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./certs:/usr/local/share/ca-certificates:ro
    network_mode: host
```
