### ISSUE TITLE
Problem running Worpress site locally

### ISSUE THREAD

**Issue by wissem-cheriguene** [urre/wordpress-nginx-docker-compose#69]
Hello,
### Environnement 
I'm on Linux Mint Ulyana 20 on a LAMP config.
### Problem & Verifications
When I launch the wordpress site on the custom domain neither HTTP or HTTPS config works and I get a 404.
I can access to phpmyadmin and mailhog containers.
The certs are installed in a certs/ folder is at the root.
No errors when I run `docker-compose up`
### Test
1. I just changed the port 80:80 to 81:81 because the 80 port is already used by my Apache server (for HTTP) locally.
- The nginx config in **docker-compose.yml** :
```
version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '81:81'
      - '443:443'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always
```
- default.conf.conf :
```
server {
    listen      81;
    listen [::]:81;
```
2. I tried to stop my local Apache server `sudo systemctl stop apache2 ` and reloading containers but I also get a 404.

If someone has an idea...
