### ISSUE TITLE
phpMyAdmin Username:Password

### ISSUE THREAD

**Issue by wchorski** [urre/wordpress-nginx-docker-compose#85]
I assume the username & password for phpmyadmin is `DB_HOST` and `DB_ROOT_PASSWORD `as per the `.yml` file

```
environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
```

Yet the login fails with these errors 

 `mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

 `mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

What is the default password?
